# Generated by Django 3.1.4 on 2020-12-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201204_1558'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
    ]
