# Generated by Django 3.1.4 on 2020-12-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201203_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='date',
        ),
    ]
